services:
  # Flask Backend
  - type: web
    name: fyp-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1

databases:
  # PostgreSQL Database  
  - name: fyp-postgres
    databaseName: fyp
    user: fyp_user
    plan: free
